FROM php:8.2-apache

RUN a2enmod rewrite headers
WORKDIR /var/www/html
COPY . /var/www/html/
COPY config.render.php /var/www/html/config.php
RUN chown -R www-data:www-data /var/www/html
EXPOSE 10000
CMD ["sh", "-c", "sed -i \"s/Listen 80/Listen ${PORT:-10000}/\" /etc/apache2/ports.conf /etc/apache2/sites-available/000-default.conf && apache2-foreground"]
